name: Build firmware for ESP32-S2 HMI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# jobs:
#   build_esp32_v5_1:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         target: ["esp32s2"]
#       fail-fast: false
#     steps:
#     - name: Checkout repo
#       uses: actions/checkout@v4
#       with:
#         ref: ${{ github.ref }}
#         submodules: 'recursive'
#     - name: ESP-IDF v5.1 build
#       uses: ./.github/actions/esp-idf-with-node
#       with:
#         target: "${{ matrix.target }}"
#         command: "idf.py set-target ${{matrix.target}} build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.2
        target: esp32s2
        path: 'esp32'
    