name: Build firmware for ESP32-S2 HMI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install Arduino core for ESP32
      run: |
        mkdir -p esp32/components
        cd esp32/components
        git clone https://github.com/espressif/arduino-esp32.git arduino

    - name: Set up ESP-IDF
      run: |
        # Download and set up ESP-IDF v5.0
        git clone -b v5.0 --recursive https://github.com/espressif/esp-idf.git /opt/esp/idf
        python3 -m pip install -r /opt/esp/idf/requirements.txt

    - name: Update idf-component-manager
      run: |
        /opt/esp/idf/install.sh
        source /opt/esp/idf/export.sh
        python3 -m pip install --upgrade idf-component-manager

    - name: esp-idf build
      run: |
        source /opt/esp/idf/export.sh
        idf.py -C esp32 build
